
name: firepush-api

image: emmachang00000/firepush-api

service:
  - name: firepush-api
    httpTargetPort: 12345

ingressroute:
  - certResolver: cf
    name: firepush-api
    domain: firepush-api.emmatest.online
    service: firepush-api

env:
  - name: FCM_PUBLIC
    valueFrom:
      secretKeyRef:
        name: fcm-pair
        key: public
  - name: FCM_PRIVATE
    valueFrom:
      secretKeyRef:
        name: fcm-pair
        key: private