
name: firepush-api

image: emmachang00000/firepush-api

service:
  - name: firepush-api
    httpTargetPort: 12345

ingressroute:
  - certResolver: cf
    name: firepush-api
    domain: firepush-api.emmatest.online
    service: firepush-api

envSecret:
- name: FCM_PUBLIC
  secretName: fcm-pair
  secretKey: public
- name: FCM_PRIVATE
  secretName: fcm-pair
  secretKey: private
  